title: Résumé
baseurl: "/resume/"
theme: "jekyll-theme-minimal-resume"
exclude:
  - README.md
  - "README_zh-CN.md"
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - crisp-minimal-theme.gemspec
  - /script
  - /fixtures
